# -*- coding: utf-8 -*-
"""a5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YhyR9Q4bJ40-X3fEZ4yAAClsI3MBtRXe

Perform the following operations on iris dataset.
1. List down the features and their types.
2. Create a box plot and histogram for each feature in the dataset.
3. Compare distributions and identify outliers.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("Iris.csv")
df

"""1. List down the features and their types."""

df.describe()

df.info()

df.shape

df.dtypes

df.columns

float64_columns = df.select_dtypes(include='float64')
float64_columns

"""2. Create a box plot and histogram for each feature in the dataset."""

sns.histplot(x = df['SepalLengthCm'])

fig, axes = plt.subplots(2, 2, figsize=(10,10))

axes[0,0].set_title("Sepal Length")
axes[0,0].hist(df['SepalLengthCm'], bins=7)

axes[0,1].set_title("Sepal Width")
axes[0,1].hist(df['SepalWidthCm'], bins=5)

axes[1,0].set_title("Petal Length")
axes[1,0].hist(df['PetalLengthCm'], bins=6)

axes[1,1].set_title("Petal Width")
axes[1,1].hist(df['PetalWidthCm'], bins=6)

"""Observations on histogram
The histogram for the petal lengths show a clear group of observations having petal lengths that are much smaller than the rest of the observations and similarly so with the petal widths.
The highest frequency of the sepal length is between 30 and 35 which is between 5.5 and 6.
The highest frequency of the sepal Width is around 70 which is between 3.0 and 3.5
The highest frequency of the petal length is around 50 which is between 1 and 2
The highest frequency of the petal width is between 40 and 50 which is between 0.0 and 0.5.
"""

sns.histplot(x = df['SepalLengthCm'],color='blue')
sns.histplot(x = df['SepalWidthCm'],color='red')
sns.histplot(x = df['PetalLengthCm'],color='green')
sns.histplot(x = df['PetalWidthCm'],color='orange')

palette = {"Iris-setosa": "blue", "Iris-versicolor": "orange", "Iris-virginica": "green"}
def graph(y):
    sns.boxplot(x="Species", y=y, data=df, palette=palette)

plt.figure(figsize=(10,10))
# Adding the subplot at the specified
# grid position

plt.subplot(221)
graph('SepalLengthCm')

plt.subplot(222)
graph('SepalWidthCm')

plt.subplot(223)
graph('PetalLengthCm')

plt.subplot(224)
graph('PetalWidthCm')

plt.show()

plot = sns.FacetGrid(df, hue="Species")
plot.map(sns.distplot, "SepalLengthCm").add_legend()

plot = sns.FacetGrid(df, hue="Species")
plot.map(sns.distplot, "SepalWidthCm").add_legend()

plot = sns.FacetGrid(df, hue="Species")
plot.map(sns.distplot, "PetalLengthCm").add_legend()

plot = sns.FacetGrid(df, hue="Species")
plot.map(sns.distplot, "PetalWidthCm").add_legend()

plt.show()

"""Observations
From the above plots, we can see that -
In the case of Sepal Length, there is a huge amount of overlapping.
In the case of Sepal Width also, there is a huge amount of overlapping.
In the case of Petal Length, there is a very little amount of overlapping.
In the case of Petal Width also, there is a very little amount of overlapping.
So we can use Petal Length and Petal Width as the classification feature.

3. Compare distributions and identify outliers.

Observations on histogram

The histogram for the petal lengths show a clear group of observations having petal lengths that are much smaller than the rest of the observations and similarly so with the petal widths.

The highest frequency of the sepal length is between 30 and 35 which is between 5.5 and 6.

The highest frequency of the sepal Width is around 70 which is between 3.0 and 3.5

The highest frequency of the petal length is around 50 which is between 1 and 2

The highest frequency of the petal width is between 40 and 50 which is between 0.0 and 0.5.

Observations

From the above dist plots, we can see that –

In the case of Sepal Length, there is a huge amount of overlapping.

In the case of Sepal Width also, there is a huge amount of overlapping.

In the case of Petal Length, there is a very little amount of overlapping.

In the case of Petal Width also, there is a very little amount of overlapping.

So we can use Petal Length and Petal Width as the classification feature.

From the box plot showing the distribution of age with respect to gender and survival status on the Titanic, we can make several observations:

Age Distribution by Gender: The box plot reveals the distribution of ages for both males and females. We can observe the median age, represented by the horizontal line inside each box, as well as the spread of ages within each gender group, indicated by the length of the boxes (interquartile range).
Survival by Age and Gender: By using the hue parameter to differentiate between survival statuses (survived and did not survive), we can see how survival outcomes vary across different age groups and genders.
Median Age: We can compare the median ages of male and female passengers, as well as the median ages of those who survived and those who did not survive within each gender group.
Age Range and Outliers: The box plot allows us to identify any outliers in the age distribution within each gender and survival status group. Outliers may represent passengers whose ages significantly deviate from the majority of passengers in their respective group.
Gender Disparities in Survival: We can assess whether there are any noticeable differences in survival rates between males and females across different age groups. For example, if there is a wider spread or higher median age among female survivors compared to male survivors, it might suggest that gender played a role in survival outcomes.
Overall, the box plot provides valuable insights into the relationship between age, gender, and survival status among Titanic passengers, allowing us to make observations about patterns and disparities in survival outcomes based on these factors.
"""
